version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    user: root
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper-data:/data:rw
      - zookeeper-logs:/datalog:rw

    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    user: root
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_HOST://clickhouse-server:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka-data:/var/lib/kafka/data:rw
      - kafka-logs:/var/lib/kafka-logs:rw

  clickhouse-server:
    image: yandex/clickhouse-server
    container_name: clickhouse-server
    depends_on:
      - kafka
    ports:
      - '8123:8123'
      - '9000:9000'
#    volumes:
#      - ./kafka.xml:/etc/clickhouse-server/config.d/kafka.xml
volumes:
  kafka-data:
  kafka-logs:
  zookeeper-data:
  zookeeper-logs:
